BaseProject/Models/Materiales/AdjuntoMaterialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Materiales
{
    public class AdjuntoMaterialViewModel
    {
        public int idAdjunto { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public int MaterialId { get; set; }
        public byte[] AdjuntoStream { get; set; }
        public string AdjuntoLength { get; set; }
    }
}

BaseProject/Models/Materiales/MaterialesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Models.Materiales
{
    public class MaterialesViewModel
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public int TipoMedidaId { get; set; }
        public string TipoMedida { get; set; }
        public int CategoriaId { get; set; }
        public string Categoria { get; set; }
        public bool Activo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string DescripcionActivo { get; set; }
        public List<SelectListItem> lstTipoMedida { get; set; }
        public List<SelectListItem> lstCategoria { get; set; }
    }
}

BaseProject/Controllers/MaterialesController.cs
using BaseProject.Models.Materiales;
using BaseProject.Repositories.CategoriaManager;
using BaseProject.Repositories.MaterialesManager;
using BaseProject.Repositories.TipoMedidaManager;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    public class MaterialesController : Controller
    {
        private readonly IMaterialesManager _materialesManager;
        private readonly ITipoMedidaManager _tipoMedida;
        private readonly ICategoriaManager _categoriaManager;

        public MaterialesController(
            IMaterialesManager materialesManager,
            ITipoMedidaManager tipoMedida,
            ICategoriaManager categoriaManager)
        {
            _materialesManager = materialesManager;
            _tipoMedida = tipoMedida;
            _categoriaManager = categoriaManager;
        }
        // GET: Materiales
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetTabla()
        {
            var data = _materialesManager.GetTablaMateriales();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearMaterial()
        {
            var model = new MaterialesViewModel
            {
                lstTipoMedida = _tipoMedida.lstTipoMedidas(),
                Activo = true,
                lstCategoria = _categoriaManager.lstTipoCategoria()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult CrearMateriales(MaterialesViewModel model)
        {
            var response = _materialesManager.CrearMetarial(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarMaterial(int idMaterial)
        {
            var model = _materialesManager.ObtenerMaterial(idMaterial);
            model.lstTipoMedida = _tipoMedida.lstTipoMedidas();
            model.lstCategoria = _categoriaManager.lstTipoCategoria();
            return View(model);
        }

        [HttpPost]
        public ActionResult EditarMaterial(MaterialesViewModel model)
        {
            var response = _materialesManager.EditarMaterial(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CambiarEstado(int Id)
        {
            var response = _materialesManager.CambiarEstado(Id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SubirAdjuntoMaterial(int idMaterial)
        {
            foreach(string fileName in Request.Files)
            {
                var file = Request.Files[fileName];
                if (file == null) continue;
                var tipoContenido = file.ContentType;
                var adjunto = new BinaryReader(file.InputStream).ReadBytes(Convert.ToInt32(file.InputStream.Length));


                var material = new AdjuntoMaterialViewModel { 
                    AdjuntoStream = adjunto,
                    nombre = file.FileName,
                    MaterialId = idMaterial,
                    tipo = tipoContenido
                };

                var response = _materialesManager.SubirAdjunto(material);

                
            }

            return null;
        }

        public ActionResult ObtenerAdjunto(int idMaterial)
        {
            var response = _materialesManager.ObtenerAdjunto(idMaterial);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DescargarAdjunto(int idAdjunto)
        {
            var response = _materialesManager.DescargarAdjunto(idAdjunto);


            return File(response.AdjuntoStream, response.tipo, response.nombre);
        }

        public ActionResult EliminarArchivo(int idAdjunto)
        {
            var response = _materialesManager.EliminarArchivo(idAdjunto);

            return Json(response, JsonRequestBehavior.AllowGet);
        }


    }
}

BaseProject/Views/Materiales/CrearMaterial.cshtml
@model BaseProject.Models.Materiales.MaterialesViewModel

<div class="panel panel-dark">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-plus-square fa-fw"></i> Nuevo Material </h1>
    </div>
    <div class="panel-body">

        <div class="row">

            <div class="col-lg-6 col-md-6 col-xs-12">
                <form id="frm" method="post">
                    <div class="form-horizontal">

                        <div class="form-group">
                            <label class="col-lg-12">Código: </label>
                            <div class="col-lg-12">
                                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Nombre: </label>
                            <div class="col-lg-12">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Descripción: </label>
                            <div class="col-lg-12">
                                @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @placeholder = "Escribir la descripcion del proudcto aqui", @rows = 10, @width = "100%", @style = "resize: none;" })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Marca: </label>
                            <div class="col-lg-12">
                                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Categoria: </label>
                            <div class="col-lg-12">
                                @Html.DropDownList("CategoriaId", Model.lstCategoria as IEnumerable<SelectListItem>, new { @class = "form-control input-lg select2", style = "width:100%;" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Tipo Medida: </label>
                            <div class="col-lg-12">
                                @Html.DropDownList("TipoMedidaId", Model.lstTipoMedida as IEnumerable<SelectListItem>, new { @class = "form-control input-lg select2", style = "width:100%;" })
                            </div>
                        </div>

                    </div>

                </form>
            </div>

            <div class="col col-lg-6 col-md-6 col-xs-12">
                <form action="@Url.Action("SubirAdjuntoMaterial", "Materiales", new { idMaterial = 0})" class="dropzone dz-clickable js-dropzone" id="mydropzone" style="height:100%">
                    <div class="dz-default dz-message">
                        <span>
                            <span class="text-center">
                                <span class="font-lg visible-xs-block visible-sm-block visible-lg-block">
                                    <span class="font-lg">
                                        <i class="fas fa-file-image text-danger"></i>
                                        </i> Drop files <span class="font-xs">to upload</span>
                                    </span><span>&nbsp;&nbsp;<h4 class="display-inline"> (Or Click)</h4></span>
                                </span>
                            </span>
                        </span>
                    </div>
                </form>
            </div>


        </div>

        <br />

        <div class="widget-footer">
            <button type='button' class='btn btn-danger js-regresar'><i class="text-lg fas fa-arrow-left"></i> Cerrar</button>
            <button type="submit" class="btn btn-success js-enviar"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
        </div>



    </div>
</div>

@section Scripts{

    <script>

        $.validator.addMethod('decimal', function(value, element) {
          return this.optional(element) || /^((\d+(\\.\d{0,2})?)|((\d*(\.\d{1,2}))))$/.test(value);
        }, "Porfavor ingrese un numero correcto con el formato 0.00");

        Dropzone.autoDiscover = false;

    $(document).ready(function () {

        $('.select2').chosen();

        $('#mydropzone').dropzone({
            autoProcessQueue: false,
            addRemoveLinks: true,
            maxFilesize: 50,
            maxFiles: 1,
            parallelUploads: 1,
            uploadMultiple: false,
            dictDefaultMessage:
                '<span class="text-center"><span class="font-lg visible-xs-block visible-sm-block visible-lg-block"><span class="font-lg"><i class="fa fa-caret-right text-danger"></i> Drop files <span class="font-xs">to upload</span></span><span>&nbsp&nbsp<h4 class="display-inline"> (Or Click)</h4></span>',
            dictResponseError: 'Error uploading file!',
            removedfile: function(file) {
                var _ref;
                (ref = file.previewElement) != null ? ref.parentNode.removeChild(file.previewElement) : void 0;
            },
            init: function() {

                myDropzone = this;

                myDropzone.on('complete',
                    function(file) {
                        window.location.href = '@Url.Action("Index","Materiales")';
                    });
            }
        });


        $(".numeric").keypress(function (e) {
            if (String.fromCharCode(e.keyCode).match(/[^0-9.]/)) return false;
        });





        $('#frm').validate({
            ignore: [],
            rules: {
                Codigo: {
                    required: true,
                    maxlength: 6
                },
                Nombre: {
                    required: true,
                    maxlength: 200
                },
                Descripcion: {
                    required: true
                },
                Marca: {
                    required: true,
                    maxlength: 200
                },
                TipoMedidaId: {
                    required: true
                },
                Precio: {
                    required: true,
                    decimal: true
                }
            },
            messages: {
                Codigo: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 6 caracteres"
                },
                Nombre: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 200 caracteres"
                },
                Descripcion: {
                    required: "Campo requerido",
                },
                TipoMedidaId: {
                    required: "Campo requerido",
                },
                Marca: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 200 caracteres"
                }

            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("CrearMateriales","Materiales")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },
                    success: function (response) {
                        if (response.Ok) {
                            myDropzone.on('sending', function (file, xhr, data) {
                                data.append("idMaterial", response.Message);
                            });

                            myDropzone.processQueue();
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;
            }
        });


    });



        $(document).on('click', '.js-enviar', function(){
            $('#frm').submit();
        })



    </script>
    
    
}

BaseProject/Views/Materiales/EditarMaterial.cshtml
@model BaseProject.Models.Materiales.MaterialesViewModel

<div class="panel panel-dark">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-edit fa-fw"></i> Editar Material @Model.Nombre</h1>
    </div>
    <div class="panel-body">

        <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-12">
                <form id="frm" method="post">
                    <div class="form-horizontal">

                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            <label class="col-lg-12">Código: </label>
                            <div class="col-lg-12">
                                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Nombre: </label>
                            <div class="col-lg-12">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Descripción: </label>
                            <div class="col-lg-12">
                                @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @placeholder = "Escribir la descripcion del proudcto aqui", @rows = 10, @width = "100%", @style = "resize: none;" })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Marca: </label>
                            <div class="col-lg-12">
                                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Categoria: </label>
                            <div class="col-lg-12">
                                @Html.DropDownList("CategoriaId", Model.lstCategoria as IEnumerable<SelectListItem>, new { @class = "form-control input-lg select2", style = "width:100%;" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Tipo Medida: </label>
                            <div class="col-lg-12">
                                @Html.DropDownList("TipoMedidaId", Model.lstTipoMedida as IEnumerable<SelectListItem>, new { @class = "form-control input-lg select2", style = "width:100%;" })
                            </div>
                        </div>

                    </div>

                </form>
            </div>

            <div class="col col-lg-6 col-md-6 col-xs-12">
                <form action="@Url.Action("SubirAdjuntoMaterial", "Materiales", new { idMaterial = Model.Id})" class="dropzone dz-clickable js-dropzone" id="mydropzone" style="height:100%">
                    <div class="dz-default dz-message">
                        <span>
                            <span class="text-center">
                                <span class="font-lg visible-xs-block visible-sm-block visible-lg-block">
                                    <span class="font-lg">
                                        <i class="fas fa-file-image text-danger"></i>
                                        </i> Drop files <span class="font-xs">to upload</span>
                                    </span><span>&nbsp;&nbsp;<h4 class="display-inline"> (Or Click)</h4></span>
                                </span>
                            </span>
                        </span>
                    </div>
                </form>
            </div>
        </div>

        

        <br />

        <div class="widget-footer">
            <button type='button' class='btn btn-danger js-regresar'><i class="text-lg fas fa-arrow-left"></i> Cerrar</button>
            <button type="submit" class="btn btn-success js-enviar"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
        </div>


    </div>
</div>


@section Scripts{
    
    <script>

        var myDropzone;

        var yaSubio = false;
        Dropzone.autoDiscover = false;

    $(document).ready(function () {

        $('.select2').chosen();

        
        $('#mydropzone').dropzone({
            autoProcessQueue: false,
            addRemoveLinks: true,
            maxFilesize: 50,
            maxFiles: 10,
            parallelUploads: 10,
            uploadMultiple: true,
            dictDefaultMessage:
                '<span class="text-center"><span class="font-lg visible-xs-block visible-sm-block visible-lg-block"><span class="font-lg"><i class="fa fa-caret-right text-danger"></i> Drop files <span class="font-xs">to upload</span></span><span>&nbsp&nbsp<h4 class="display-inline"> (Or Click)</h4></span>',
            dictResponseError: 'Error uploading file!',
            removedfile: function(file) {
                if (file.id)
                    DeleteFile(file);
            },
            init: function() {

                myDropzone = this;

                $.ajax({
                    url: '@Url.Action("ObtenerAdjunto", "Materiales")',
                    type: "GET",
                    data: { idMaterial: '@Model.Id' },
                    success: function (adjuntos) {
                        console.log(adjuntos);

                        var file = { name: adjuntos.nombre, size: Number(adjuntos.AdjuntoLength), type: adjuntos.tipo, id: adjuntos.idAdjunto };
                        var idAdjunto = adjuntos.idAdjunto;
                        myDropzone.options.addedfile.call(myDropzone, file);
                        myDropzone.files.push(file)
                        myDropzone.on("complete", function (file) {
                            var a = document.createElement('a');
                            a.setAttribute('href', "@Url.Action("DescargarAdjunto", "Materiales")?&idAdjunto=" + idAdjunto);
                            a.setAttribute('class', 'dz-remove js-download');
                            a.setAttribute('target', '_blank');
                            a.innerHTML = "Download";
                            $(file.previewTemplate).find('.js-download').remove();
                            file.previewTemplate.appendChild(a);
                        });
                        myDropzone.emit("complete", file);


                    },
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    }
                });

                myDropzone.on('complete',
                    function(file) {
                        if (yaSubio) {
                            window.location.href = '@Url.Action("Index","Materiales")';
                        }
                    });

            }
                
        });



        $('#frm').validate({
            ignore: [],
            rules: {
                Codigo: {
                    required: true,
                    maxlength: 6
                },
                Nombre: {
                    required: true,
                    maxlength: 200
                },
                Descripcion: {
                    required: true
                },
                Marca: {
                    required: true,
                    maxlength: 200
                },
                TipoMedidaId: {
                    required: true
                }
            },
            messages: {
                Codigo: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 6 caracteres"
                },
                Nombre: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 200 caracteres"
                },
                Descripcion: {
                    required: "Campo requerido",
                },
                Marca: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 200 caracteres"
                },
                TipoMedidaId: {
                    required: "Campo requerido",
                }

            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("EditarMaterial","Materiales")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },
                    success: function (data) {
                        if (data.Ok) {
                            if (myDropzone.getQueuedFiles().length > 0) {
                                LoadWaitNotification();
                                yaSubio = true;
                                myDropzone.processQueue();
                                UnloadWaitNotification();
                            } else {
                                window.location.href = '@Url.Action("Index","Materiales")';
                            }
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;
            }
        });


    });


        function DeleteFile(file) {

            $.ajax({
                url: '@Url.Action("EliminarArchivo", "Materiales")',
                type: "get",
                data: { idAdjunto: file.id },
                beforeSend: function () {
                    LoadWaitNotification();
                },
                complete: function () {
                    UnloadWaitNotification();
                },
                success: function (result) {
                    if (result.Ok) {
                        var _ref;
                        (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
                        
                    } else {
                        
                    }
                }
            });


        }

        $(document).on('click', '.js-enviar', function(){
            $('#frm').submit();
        })

        $(document).on('click', '.js-regresar', function () {
            window.location.href = '@Url.Action("Index","Materiales")';
        });

    </script>

}
    

BaseProject/Views/Materiales/Index.cshtml
<div class="panel panel-dark">
    <div class="panel-heading">
        <div class="panel-control">

            <a class="btn btn-success js-crear"><i class="fa fa-plus-circle fa-fw"></i> Nuevo Material</a>
        </div>
        <h3 class="panel-title"> <i class="fas fa-toolbox fa-fw"></i>Listado de Materiales</h3>
    </div>

    <div class="panel-body">
        <table class="table table-responsive table-bordered table-hover" style="width:100%;" id="dtMateriales">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Tipo Medida</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

    </div>
</div>

@section Scripts{

    <script>

        var dtMateriales;

        $(document).ready(function () {

            dtMateriales = $('#dtMateriales').DataTable({
                autoWidth: true,
                responsive: true,
                language: {
                    "emptyTable": "No se encontraron resultados.",
                    "search": '<div class="icon-addon addon-md"><label for="search" class="ion-search"></label>',
                    "paginate": {
                        first: "Primero",
                        previous: "Anterior",
                        next: "Siguiente",
                        last: "Ultimo"
                    },
                    "lengthMenu": " _MENU_ ",
                    "info": "Mostrando registros del _START_ al _END_ de _TOTAL_ registros totales.",
                    "infoEmpty": "No hay registros para mostrar.",
                },
                "ajax": {
                    url: '@Url.Action("GetTabla", "Materiales")',
                    "type": "GET",
                    "datatype": "json",
                    "error": function (xhr, status, error) { }
                },
                columns: [
                    { "data": "Codigo", "autoWidth": true },
                    { "data": "Nombre", "autoWidth": true },
                    { "data": "Marca", "autoWidth": true },
                    { "data": "TipoMedida", "autoWidth": true },
                    {
                        data: null,
                        render: function (data) {
                            if (data.Activo) {
                                return '<div class="label label-success">Si</div>';
                            } else {
                                return '<div class="label label-danger">No</div>';
                            }
                        }
                    },
                    {
                        "data": "null",
                        render: function (data, type, row, meta) {

                            var activar = "";

                            if (row.Activo) {
                                activar = '<li><a href="javascript: void(0)" data-material="' + row.Id + '" name="Desactivar"> Desactivar</a>';
                            } else {
                                activar = '<li><a href="javascript: void(0)" data-material="' + row.Id + '" name="Activar"> Activar</a>';
                            }


                            return '<div class="btn-group"> <button class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Acciones <i class="fa fa-caret-down fa-lg"></i> </button>' +
                                '<ul class="dropdown-menu">' +
                                '<li><a href="javascript: void(0)" data-material="' + row.Id + '" name="Edit">Editar</a>' +
                                activar +
                                '</ul></div>';
                        }
                    }
                ]
            });

        });

        $(document).on('click', '.js-crear', function () {

            window.location.href = '@Url.Action("CrearMaterial","Materiales")';


        });


        $('#dtMateriales tbody').on('click', 'a[name="Edit"]', function () {

            var material = $(this).data('material');

            window.location.href = '@Url.Action("EditarMaterial","Materiales")?idMaterial='+material;

        });

        $('#dtMateriales tbody').on('click', 'a[name="Desactivar"]', function () {

            var material = $(this).data('material');

            var data = { Id: material };

            DeshabilitarRegistro(data, dtMateriales, '/Materiales/CambiarEstado/', 'Desea inhabilitar el Material?','text-danger');

        });

        $('#dtMateriales tbody').on('click', 'a[name="Activar"]', function () {

            var material = $(this).data('material');

            var data = { Id: material };

            DeshabilitarRegistro(data, dtMateriales, '/Materiales/CambiarEstado/', 'Desea habilitar el material?','text-primary');

            

        });


    </script>
    
}