BaseProject/Controllers/CategoriaController.cs
using BaseProject.Models.Categoria;
using BaseProject.Repositories.CategoriaManager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICategoriaManager _categoriaManager;

        public CategoriaController(ICategoriaManager categoriaManager)
        {
            _categoriaManager = categoriaManager;
        }

        // GET: Categoria
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ObtenerTabla()
        {
            var data = _categoriaManager.ObtenerListado();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearCategoria()
        {
            var model = new CategoriaViewModel {
                Activo = true
            };
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult CrearCategoria(CategoriaViewModel model)
        {
            var response = _categoriaManager.Crear(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarCategoria(int idCategoria)
        {
            var model = _categoriaManager.ObtenerById(idCategoria);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult EditarCategoria(CategoriaViewModel model)
        {
            var response = _categoriaManager.Editar(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CambiarEstado(int Id)
        {
            var response = _categoriaManager.CambiarEstado(Id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

    }
}

BaseProject/Controllers/InventarioController.cs
using BaseProject.Models;
using BaseProject.Models.Inventario;
using BaseProject.Repositories.InventarioManager;
using BaseProject.Repositories.SeguridadManager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    public class InventarioController : Controller
    {
        private readonly IInventaioManager _inventarioManager;
        private readonly ISeguridadManager _seguridadManeger;

        public InventarioController(
            IInventaioManager inventaioManager,
            ISeguridadManager seguridadManager)
        {
            _inventarioManager = inventaioManager;
            _seguridadManeger = seguridadManager;
        }

        // GET: Inventario
        public ActionResult Index()
        {
            var result = _seguridadManeger.BuscarUsuarioSucursal(User.Identity.Name);
            return View(result);
        }

        public JsonResult GetTabla()
        {
            var data = _inventarioManager.GetTabla(1);

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult AgregarMaterial(int idSucursal)
        {
            var lst = _inventarioManager.GetMaterialesPorAgregar(idSucursal);

            if(lst.Count > 0)
            {
                var model = new InventarioViewModel
                {
                    SucursalId = idSucursal,
                    lstMateriales = lst
                };

                return PartialView(model);
            }

            return Json(new ResponseMessage { Ok = false, Message = $"Ya se han agregado todos los materiales disponibles a esta sucursal" }, JsonRequestBehavior.AllowGet);
            

        }

        [HttpPost]
        public JsonResult AgregarMaterial(InventarioViewModel model)
        {
            var response = _inventarioManager.AgregarMaterial(model);

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult VerMaterialInventario(int idInventario)
        {
            var model = _inventarioManager.VerMaterial(idInventario);
            model.Sucursal = _seguridadManeger.BuscarUsuarioSucursal(User.Identity.Name).Sucursal;

            return PartialView(model);
        }

    }
}

BaseProject/Controllers/KardexController.cs
using BaseProject.Models.Kardex;
using BaseProject.Repositories.KardexManager;
using BaseProject.Repositories.SeguridadManager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    [Authorize]
    public class KardexController : BaseController
    {
        private readonly IKardexManager _kardexManager;
        public KardexController(
            ISeguridadManager seguridadManager,
            IKardexManager kardexManager
            ): base(seguridadManager) {
            _kardexManager = kardexManager;
        }
        // GET: Kardex
        public ActionResult Index()
        {
            var model = ObtenerSucuralUsuario(User.Identity.Name);
            
            return View(model);
        }

        [HttpGet]
        public JsonResult ObtenerTabla()
        {
            var data = _kardexManager.ObtenerTabla(ObtenerSucuralUsuario(User.Identity.Name).SucursalId);
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearTransaccion(int SucursalId)
        {
            var model = _kardexManager.ObtenerModeloCrear(SucursalId);
            return View(model);
        }

        [HttpPost]
        public ActionResult CrearTransaccion(KardexViewModel model)
        {
            var response = _kardexManager.CrearTransaccion(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult VerificarCantidad(int MaterialId, int Cantidad)
        {
            var result = _kardexManager.VerificarCantidad(MaterialId, Cantidad);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult VerTransaccion(int idTransacion)
        {
            var model = _kardexManager.VerTransacion(idTransacion);
            model.Sucursal = ObtenerSucuralUsuario(User.Identity.Name).Sucursal;
            return PartialView(model);
        }

    }
}

BaseProject/Controllers/SeguridadController.cs
using BaseProject.Models;
using BaseProject.Models.Seguridad;
using BaseProject.Repositories.SeguridadManager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    public class SeguridadController : Controller
    {
        private readonly ISeguridadManager _seguridad;

        public SeguridadController(ISeguridadManager seguridad)
        {
            _seguridad = seguridad;
        }

        #region Usuario

        // GET: Seguridad
        public ActionResult Usuario()
        {
            return View();
        }

        public JsonResult GetTablaUsuario()
        {
            return Json(new { data = _seguridad.ObtenerUsuarios() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CrearUsuario()
        {
            return PartialView(new UsuarioViewModel
            {
                lstSucursal = _seguridad.Sucurales()
            });
        }

        [HttpPost]
        public ActionResult CrearUsuario(UsuarioViewModel model)
        {
            var response = _seguridad.CrearUsuario(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarUsuario(string usuario)
        {
            var data = _seguridad.ObtenerUsuario(usuario);
            return PartialView(data);
        }

        [HttpPost]
        public ActionResult EditarUsuario(UsuarioViewModel model)
        {
            var response = _seguridad.EditarUsuario(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ChangePassword(string usuario)
        {
            var model = _seguridad.ObtenerUsuario(usuario);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult ChangePassword(UsuarioViewModel model)
        {
            var response = _seguridad.CambiarContrasena(model);

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Roles

        public ActionResult Roles()
        {
            return View();
        }

        public JsonResult GetTablaRoles()
        {
            var data = _seguridad.ObtenerListaRoles();
            return Json(new { data = data}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearRol()
        {
            var model = _seguridad.ModelCrearRol();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult CrearRol(RolViewModel model)
        {
            var response = _seguridad.CrearRol(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarRol(string RoleName)
        {
            var model = _seguridad.ObtenerRolPorNombre(RoleName);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult EditarRol(RolViewModel model)
        {
            var response = _seguridad.EditarRol(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Sucursales

        public ActionResult Sucursales()
        {
            return View();
        }

        public JsonResult GetTablaSucursales()
        {
            return Json(new { data = _seguridad.ObtenerSucursales() }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearSucursal()
        {
            return PartialView(new SucursalViewModel { });
        }

        [HttpPost]
        public ActionResult CrearSucursal(SucursalViewModel model)
        {
            var response = _seguridad.CrearSucursal(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarSucursal(int idSucursal)
        {
            var sucursal = _seguridad.ObtenerSucursalPorId(idSucursal);
            return PartialView(sucursal);
        }

        [HttpPost]
        public ActionResult EditarSucursal(SucursalViewModel model)
        {
            var response = _seguridad.EditarSucursal(model);

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region PermisosPorUsuario

        public ActionResult AsignarPermisos(string usuario)
        {
            var datosUsuario = _seguridad.ObtenerUsuario(usuario);

            var model = new PermisosPorUsuarioViewModel
            {
                Nombre = datosUsuario.nombre,
                UserId = datosUsuario.UserId,
                Usuario = usuario
            };

            return PartialView(model);
        }

        public ActionResult ObtenerPermisos(Guid userId)
        {
            var data = _seguridad.ObtenerRoles(userId);

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarSeleccionPermisos(Guid UserId, List<PermisosPorUsuarioViewModel> ListaDetalle)
        {
            var response = _seguridad.AsignarRoles(UserId, ListaDetalle);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

    }
}

BaseProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-us">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>VIDRIERIA</title>

    @*<link rel="shortcut icon" href="~/img/bp-ico.icoo" type="image/x-icon" />*@
    <link runat="server" rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="favicon.ico" type="image/ico" />
    <!--STYLESHEET-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")




    <link href="~/Template/css/themes/type-d/theme-dark.min.css" rel="stylesheet" />
</head>

<body>
    @Html.Partial("_PartialModal")
    <div id="container" class="effect aside-float aside-bright mainnav-lg" style="background-image: url('../../Template/premium/boxed-bg/polygon/bg/3.jpg'); background-repeat: no-repeat; background-size: cover; background-attachment: fixed;">

        <!--NAVBAR-->
        <!--===================================================-->
        @Html.Partial("_PartialHeader")
        <!--===================================================-->
        <!--END NAVBAR-->

        <div class="boxed">

            <!--CONTENT CONTAINER-->
            <!--===================================================-->
            <div id="content-container">
                <div id="page-head">

                    <!--Page Title-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    @*<div id="page-title">
                        <h1 class="page-header text-center"><b>BP WALLET</b></h1>
                        </div>*@
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <!--End page title-->
                    <!--Breadcrumb-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    @*<ol class="breadcrumb">
                            <li><a href="#"><i class="pli-home"></i></a></li>
                            <li><a href="#">Library</a></li>
                            <li class="active">Data</li>
                        </ol>*@
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <!--End breadcrumb-->


                </div>

                <!--Page content-->
                <!--===================================================-->
                <div id="page-content">
                    @RenderBody()
                </div>


                <!--Floating Button-->
                <!--===================================================-->
                @*@if (User.IsInRole("Registros_Acceso"))
                    {
                        <a class="btn btn-success float in" href="javascript:void(0)" onclick="MostrarCrearRegistro()" style="position: fixed; animation: jellyIn 0.8s ease 0s 1 normal none running;">
                            <i class="fa fa-pencil-alt my-float"></i>
                        </a>

                        <div class="label-container">
                            <div class="label-text">Nuevo Registro</div>
                            <i class="fa fa-play label-arrow"></i>
                        </div>

                    }*@

                <!--===================================================-->
                <!--End page content-->
            </div>
            <!--===================================================-->
            <!--END CONTENT CONTAINER-->
            <!--MAIN NAVIGATION-->
            <!--===================================================-->
            @Html.Partial("_PartialMenu")
            <!--===================================================-->
            <!--END MAIN NAVIGATION-->
            <!--ASIDE-->
            <!--===================================================-->
            @Html.Partial("_PartialAside")
            <!--===================================================-->
            <!--END ASIDE-->

        </div>



        <!-- FOOTER -->
        <!--===================================================-->
        @*@Html.Partial("_PartialFooter")*@
        <!--===================================================-->
        <!-- END FOOTER -->
        <!-- SCROLL PAGE BUTTON -->
        <!--===================================================-->
        <button class="scroll-top btn">
            <i class="pci-chevron chevron-up"></i>
        </button>

        

        


        <!--===================================================-->
    </div>
    <!--===================================================-->
    <!-- END OF CONTAINER -->
    <!--JAVASCRIPT-->
    <!--=================================================-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/bundles/personalized")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

    <script>

        window.FontAwesomeConfig = { searchPseudoElements: true };

    </script>

</body>
</html>

<style>

    .error {
        color: #a94442;
        /*margin-left: 12px;*/
    }
    .status2 {
        position: relative;
        background-repeat: no-repeat;
        background-position: center;
    }

</style>

BaseProject/Views/Shared/_PartialAside.cshtml
<aside id="aside-container">
    <div id="aside">
        <div class="nano">
            <div class="nano-content">

                <!--Nav tabs-->
                <!--================================-->
                <ul class="nav nav-tabs nav-justified">
                    <li class="active">
                        <a href="#demo-asd-tab-1" data-toggle="tab">
                            <i class="pli-speech-bubble-7"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#demo-asd-tab-2" data-toggle="tab">
                            <i class="pli-information"></i>
                            Reports
                        </a>
                    </li>
                    <li>
                        <a href="#demo-asd-tab-3" data-toggle="tab">
                            <i class="pli-wrench"></i>
                            Settings
                        </a>
                    </li>
                </ul>
               
                <!--================================-->
                <!--End nav tabs-->
                <!-- Tabs Content -->
                <!--================================-->
                <div class="tab-content">

                    <!--First tab-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <div class="tab-pane fade in active" id="demo-asd-tab-1">
                        <p class="pad-all text-lg">First tab</p>
                        <div class="pad-hor">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                            sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                            ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate
                            velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan
                            et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </div>
                    </div>
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <!--End first tab-->
                    <!--Second tab-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <div class="tab-pane fade" id="demo-asd-tab-2">
                        <p class="pad-all text-lg">Second tab</p>
                        <div class="pad-hor">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                            sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                            ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate
                            velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan
                            et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </div>
                    </div>
                    <!--End second tab-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <!--Third tab-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <div class="tab-pane fade" id="demo-asd-tab-3">
                        <p class="pad-all text-lg">Third tab</p>
                        <div class="pad-hor">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                            sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                            ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate
                            velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan
                            et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </div>
                    </div>
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

                </div>
            </div>
        </div>
    </div>
</aside>

BaseProject/Views/Shared/_PartialFooter.cshtml
<footer id="footer">

    <!-- Visible when footer positions are fixed -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <div class="show-fixed pad-rgt pull-right">
        You have <a href="#" class="text-main"><span class="badge badge-danger">3</span> pending action.</a>
    </div>



    <!-- Visible when footer positions are static -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <div class="hide-fixed pull-right pad-rgt">
        14GB of <strong>512GB</strong> Free.
    </div>



    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Remove the class "show-fixed" and "hide-fixed" to make the content always appears. -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

    <p class="pad-lft">&#0169; 2018 Your Company</p>



</footer>

BaseProject/Views/Shared/_PartialHeader.cshtml
<header id="navbar">
    <div id="navbar-container" class="boxed">

        <!--Brand logo & name-->
        <!--================================-->
        <div class="navbar-header">
            <a href="index.html" class="navbar-brand">
                @*<img src="~/Template/img/logo.png" alt="Nifty Logo" class="brand-icon">*@
                <img src="~/img/Logo-mini.png" alt="Logo" class="brand-icon"/>
                <div class="brand-title">
                    <span class="brand-text"> El Cirstal</span>
                </div>
            </a>
        </div>

        <div class="navbar-content clearfix">
            <ul class="nav navbar-top-links">


                <li class="tgl-menu-btn">
                    <a class="mainnav-toggle" href="#">
                        <i class="ion-navicon-round" style="font-size: 20px;"></i>
                    </a>
                </li>


                <li>

             </li>









            </ul>
            <ul class="nav navbar-top-links">


                

                <li id="dropdown-user" class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle text-right">
                        <span class="ic-user pull-right">
                            
                            <img class="img-circle img-user media-object" src="~/Template/img/profile-photos/1.png" alt="Profile Picture">

                        </span>
                        
                    </a>


                    <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right panel-default">
                        <ul class="head-list">


                            <li>
                                <a href="@Url.Action("LogOff", "Account")"><i class="pli-unlock icon-lg icon-fw"></i> Cerrar Sesion</a>
                            </li>
                        </ul>
                    </div>
                </li>

                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End user dropdown-->
                <li>
                    @*<a href="#" class="aside-toggle">
                <i class="ion-plus-circled" style="font-size: 20px;"></i>
            </a>*@
                </li>



            </ul>
        </div>
        <!--================================-->
        <!--End Navbar Dropdown-->

    </div>
</header>

BaseProject/Views/Shared/_PartialMenu.cshtml
<nav id="mainnav-container">
    <div id="mainnav">
        <!--OPTIONAL : ADD YOUR LOGO TO THE NAVIGATION-->
        <!--It will only appear on small screen devices.-->
        <link href="~/Template/css/Layout.css" rel="stylesheet" />
        <div class="mainnav-brand">
            <a href="index.html" class="brand">
                <img src="~/img/Logo-mini.png" width="50%"  alt="Logo" class="brand-icon" />
            
                <span class="brand-text"> El Cirstal</span>
            </a>
            <a href="#" class="mainnav-toggle"><i class="ion-close-round icon-lg"></i></a>
        </div>

        <!--Menu-->
        <!--================================-->
        <div id="mainnav-menu-wrap">
            <div class="nano">
                <div class="nano-content">

                    <!--Profile Widget-->
                    <!--================================-->
                    <div id="mainnav-profile" class="mainnav-profile">
                        <div class="profile-wrap text-center">
                            <div class="pad-btm">
                                <img class="img-circle img-md" src="~/Template/img/profile-photos/1.png" alt="Profile Picture">
                            </div>
                            <a href="#profile-nav" class="box-block" data-toggle="collapse" aria-expanded="false">
                                <span class="pull-right dropdown-toggle">
                                    <i class="dropdown-caret"></i>
                                </span>
                                <p class="mnp-name">@User.Identity.Name</p>
                                <span class="mnp-desc">Usuario</span>
                            </a>
                        </div>
                        <div id="profile-nav" class="collapse list-group bg-trans">
                            <a href="#" class="list-group-item">
                                <i class="fas fa-key"></i> Cambiar Contraseña
                            </a>
                            <a href="@Url.Action("LogOff", "Account")" class="list-group-item">
                                <i class="pli-unlock icon-lg icon-fw"></i> Cerrar Sesion
                            </a>
                        </div>
                    </div>


                    <ul id="mainnav-menu" class="list-group">

                        <li class="list-header">Seguridad</li>
                        <li>
                            <a href="@Url.Action("Usuario","Seguridad")">
                                <i class="fa fa-user fa-fw"></i>
                                <span class="menu-title"><strong>Usuarios</strong></span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Roles","Seguridad")">
                                <i class="fas fa-user-lock fas-fw"></i>
                                <span class="menu-title"><strong>Permisos</strong></span>
                            </a>
                        </li>

                        <li class="list-divider"></li>
                    </ul>

                    <ul id="mainnav-menu" class="list-group">

                        <li class="list-header">Configuraciones</li>
                        <li>
                            <a href="@Url.Action("Sucursales","Seguridad")">
                                <i class="fa fa-building fa-fw"></i>
                                <span class="menu-title"><strong>Sucursales</strong></span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","TipoMedida")">
                                <i class="fas fa-ruler-combined fa-fw"></i>
                                <span class="menu-title"><strong>Tipo Medida</strong></span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Materiales")">
                                <i class="fas fa-toolbox fa-fw"></i>
                                <span class="menu-title"><strong>Materiales</strong></span>
                            </a>
                            <a href="@Url.Action("Index","Categoria")">
                                <i class="fas fa-list-alt fa-fw"></i>
                                <span class="menu-title"><strong>Categorias</strong></span>
                            </a>
                        </li>

                        <li class="list-divider"></li>
                    </ul>

                    <ul id="mainnav-menu" class="list-group">
                        <li class="list-header">Inventario</li>
                        <li>
                            <a href="@Url.Action("Index","Inventario")">
                                <i class="fas fa-boxes fa-fw"></i>
                                <span class="menu-title"><strong>Inventario</strong></span>
                            </a>
                            <a href="@Url.Action("Index","Kardex")">
                                <i class="fas fa-exchange-alt fa-fw"></i>
                                <span class="menu-title"><strong>Kardex</strong></span>
                            </a>
                        </li>
                    </ul>


                </div>
            </div>
        </div>

    </div>
</nav>