BaseProject/Models/Producto/ProductoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Models.Producto
{
    public class ProductoViewModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int CategoriaProductoId { get; set; }
        public string Categoria { get; set; }
        public bool Activo { get; set; }
        public List<SelectListItem> lstCategoria { get; set; }
        public List<SelectListItem> lstProducto { get; set; }
        public List<ProductoDetalleViewModel> lstDetalle { get; set; }
    }


    public class ProductoDetalleViewModel
    {
        public int Id { get; set; }
        public int MaterialId { get; set; }
        public string Material { get; set; }
        public string Formula { get; set; }
    }

    public class AdjuntoProductoViewModel
    {
        public int idAdjunto { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public int ProductoId { get; set; }
        public byte[] AdjuntoStream { get; set; }
        public string AdjuntoLength { get; set; }
    }

}

BaseProject/Controllers/ProductoController.cs
using BaseProject.Models.Producto;
using BaseProject.Repositories.ProductoManager;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProductoManager _productoManager;

        public ProductoController(IProductoManager productoManager)
        {
            _productoManager = productoManager;
        }

        // GET: Producto
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ObtenerTabla()
        {
            var data = _productoManager.ObtenerTabla();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearProducto()
        {
            var model = _productoManager.ObtenerModeloCrear();
            return View(model);
        }

        [HttpPost]
        public ActionResult CrearProducto(ProductoViewModel model)
        {
            var result = _productoManager.CrearProducto(model);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SubirAdjuntoProducto(int idProducto)
        {
            foreach (string fileName in Request.Files)
            {
                var file = Request.Files[fileName];
                if (file == null) continue;
                var tipoContenido = file.ContentType;
                var adjunto = new BinaryReader(file.InputStream).ReadBytes(Convert.ToInt32(file.InputStream.Length));


                var material = new AdjuntoProductoViewModel
                {
                    AdjuntoStream = adjunto,
                    nombre = file.FileName,
                    ProductoId = idProducto,
                    tipo = tipoContenido
                };

                var response = _productoManager.SubirAdjunto(material);


            }

            return null;
        }

        [HttpGet]
        public ActionResult EditarProducto(int idProducto)
        {
            var model = _productoManager.ObtenerProducto(idProducto);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditarProducto(ProductoViewModel model)
        {
            var response = _productoManager.EditarProducto(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ObtenerAdjunto(int idProducto)
        {
            var result = _productoManager.ObtenerAdjuntoProducto(idProducto);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DescargarAdjunto(int idProducto)
        {
            var result = _productoManager.ObtenerAdjuntoProducto(idProducto);
            return File(result.AdjuntoStream, result.tipo, result.nombre);
        }

        public JsonResult GetDetalleProducto(int idProducto)
        {
            var data = _productoManager.ObtenerDetalleProducto(idProducto);

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EliminarDetalle(int idDetalle)
        {
            var result = _productoManager.EliminarDetalle(idDetalle);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AgregarDetalle(ProductoDetalleViewModel detalle)
        {
            var result = _productoManager.AgregarDetalle(detalle);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CambiarEstado(int Id)
        {
            var response = _productoManager.CambiarEstado(Id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult VerProducto(int idProducto)
        {
            var model = _productoManager.VerProducto(idProducto);
            return PartialView(model);
        }

        public ActionResult ObtenerImagen(int idProducto)
        {
            var result = _productoManager.ObtenerAdjuntoProducto(idProducto);
            return File(result.AdjuntoStream, result.tipo);
        }

    }
}

BaseProject/Views/Producto/CrearProducto.cshtml
@model BaseProject.Models.Producto.ProductoViewModel

<div class="panel panel-dark">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-plus-square fa-fw"></i> Nuevo Producto </h1>
    </div>
    <div class="panel-body">

        <div class="row">

            <div class="col-lg-6 col-md-6 col-xs-12">
                <form id="frm" method="post">
                    <div class="form-horizontal">

                        <div class="form-group">
                            <label class="col-lg-12">Nombre: </label>
                            <div class="col-lg-12">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Descripción: </label>
                            <div class="col-lg-12">
                                @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @placeholder = "Escribir la descripcion del proudcto aqui", @rows = 10, @width = "100%", @style = "resize: none;" })

                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-lg-12">Categoria Producto: </label>
                            <div class="col-lg-12">
                                @Html.DropDownList("CategoriaProductoId", Model.lstCategoria as IEnumerable<SelectListItem>, new { @class = "form-control input-lg select2", style = "width:100%;" })
                            </div>
                        </div>

                        @Html.HiddenFor(model => model.Activo)

                    </div>

                </form>
            </div>

            <div class="col col-lg-6 col-md-6 col-xs-12">
                <form action="@Url.Action("SubirAdjuntoProducto", "Producto", new { idProducto = 0})" class="dropzone dz-clickable js-dropzone" id="mydropzone" style="height:100%">
                    <div class="dz-default dz-message">
                        <span>
                            <span class="text-center">
                                <span class="font-lg visible-xs-block visible-sm-block visible-lg-block">
                                    <span class="font-lg">
                                        <i class="fas fa-file-image text-danger"></i>
                                        </i> Drop files <span class="font-xs">to upload</span>
                                    </span><span>&nbsp;&nbsp;<h4 class="display-inline"> (Or Click)</h4></span>
                                </span>
                            </span>
                        </span>
                    </div>
                </form>
            </div>


        </div>

        <div class="row">

            <div class="col col-lg-12 col-md-12 col-sm-12">
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Agregar Materiales</legend>
                    <form method="post" id="frmMaterial">
                        <div class="form-horizontal">
                            <div class="row">

                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="form-group">
                                        <label class="col-lg-12">Material</label>

                                        <div class="col-md-12">
                                            @Html.DropDownList("Material", Model.lstProducto as IEnumerable<SelectListItem>, new { @class = "form-control select2", style = "width:100%;" })

                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="form-group">
                                        <label class="col-lg-12">Formula: </label>
                                        <div class="col-md-10 col-sm-10 col-lg-10">
                                            <input class="form-control numeric" name="formula" id="formula" type="text" />
                                        </div>
                                        <div class="col-md-1 col-sm-1 col-lg-1">
                                            <div class="btn btn-primary btn-sm js-addmaterial" type="button" data-toggle="tooltip" data-placement="top" title="Agregar Material"><i class="fa fa-plus"></i></div>
                                        </div>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </form>
                </fieldset>
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Materiales</legend>

                    <table class="table table-reponsive table-bordered" id="dtMateriales" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th data-class="expand">Materiales</th>
                                <th data-class="expand">Formula</th>
                                <th data-class="expand"></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>

                </fieldset>
            </div>

        </div>


        <br />

        <div class="widget-footer">
            <button type='button' class='btn btn-danger js-regresar'><i class="text-lg fas fa-arrow-left"></i> Cerrar</button>
            <button type="submit" class="btn btn-success js-enviar"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
        </div>



    </div>
</div>

@section Scripts{
    
    <script>

        Dropzone.autoDiscover = false;
        var dtMateriales;
        var Materiales = [];

        $(document).ready(function () {

            $('.select2').chosen();

            $('#dtMateriales').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "paging": false,
                "ordering": false,
                "info": false,
                "searching": false
            });

            dtMateriales = $('#dtMateriales').DataTable();

            $('#mydropzone').dropzone({
                autoProcessQueue: false,
                addRemoveLinks: true,
                maxFilesize: 50,
                maxFiles: 1,
                parallelUploads: 1,
                uploadMultiple: false,
                dictDefaultMessage:
                    '<span class="text-center"><span class="font-lg visible-xs-block visible-sm-block visible-lg-block"><span class="font-lg"><i class="fa fa-caret-right text-danger"></i> Drop files <span class="font-xs">to upload</span></span><span>&nbsp&nbsp<h4 class="display-inline"> (Or Click)</h4></span>',
                dictResponseError: 'Error uploading file!',
                removedfile: function(file) {
                    var _ref;
                    (ref = file.previewElement) != null ? ref.parentNode.removeChild(file.previewElement) : void 0;
                },
                init: function() {

                    myDropzone = this;

                    myDropzone.on('complete',
                        function(file) {
                            window.location.href = '@Url.Action("Index","Producto")';
                        });
                }
            });
        });


        $('#frm').validate({
            ignore: [],
            rules: {
                Nombre: {
                    required: true,
                    maxlength: 150
                },
                Descripcion: {
                    required: true,
                    maxlength: 400
                },
                CategoriaProductoId: {
                    required: true
                }
            },
            messages: {
                Nombre: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 150 caracteres"
                },
                Descripcion: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 400 caracteres"
                },
                CategoriaProductoId: {
                    required: "Campo requerido"
                }
            },
            submitHandler: function (form) {

                var model = {
                    Nombre: $('#Nombre').val(),
                    Descripcion: $('#Descripcion').val(),
                    CategoriaProductoId: $('#CategoriaProductoId option:selected').val(),
                    Activo: '@Model.Activo',
                    lstDetalle: Materiales
                };


                $.ajax({
                    url: "@Url.Action("CrearProducto","Producto")",
                    type: "post",
                    dataType: "JSON",
                    data: {model: model},
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },
                    success: function (response) {
                        if (response.Ok) {
                            myDropzone.on('sending', function (file, xhr, data) {
                                data.append("idProducto", response.Message);
                            });

                            myDropzone.processQueue();
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;

            }
        })

        $('#frmMaterial').validate({
            ignore: [],
            rules: {
                Material: {
                    required: true,

                },
                formula: {
                    required: true
                }
            },
            messages: {
                Material: {
                    required: "Campo requerido",
                },
                formula: {
                    required: "Campo requerido"
                }
            },
            submitHandler: function (form) {

                var material = $('#Material option:selected').text();
                var formula = $('#formula').val();

                var existe = false;

                dtMateriales.rows().every(function (rowIdx, tableLopp, rowLopp) {
                    if (this.data()[0] === material) {
                        existe = true;
                    }

                });

                if (existe) {
                    var ErrorData = {
                        Ok: false,
                        Message: "El material ya se ha agregado!"
                    };
                    AlertaAjax(ErrorData);
                } else {
                    var materialId = $('#Material option:selected').val();

                    var object = {
                        MaterialId: materialId,
                        Formula: formula
                    };

                    Materiales.push(object);
                    console.log(Materiales);
                    dtMateriales.row.add([
                        material,
                        formula,
                        '<button class="btn btn-danger" data-material="'+materialId+'" ><i class="fa fa-trash" aria-hidden="true"></i></button>'
                    ]).draw();
                    $('#formula').val('');
                }

            }
        });


        $(document).on('click', '.js-addmaterial', function () {
            $('#frmMaterial').submit();
        });

         $(document).on('click', '.js-enviar', function () {
            $('#frm').submit();
        }); 

    </script>

}

    

BaseProject/Views/Producto/Index.cshtml
<div class="panel panel-dark">
    <div class="panel-heading">
        <div class="panel-control">

            <a class="btn btn-success js-crear"><i class="fa fa-plus-circle fa-fw"></i> Nuevo Producto</a>
        </div>
        <h3 class="panel-title"> <i class="fas fa-list-alt fa-fw"></i>Listado de Productos</h3>
    </div>

    <div class="panel-body">
        <table class="table table-responsive table-bordered table-hover" style="width:100%;" id="dtProductos">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Categoria</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

@section Scripts{

    <script>

        var dtProductos;

        $(document).ready(function () {


            dtProductos = $('#dtProductos').DataTable({
                autoWidth: true,
                responsive: true,
                language: {
                    "emptyTable": "No se encontraron resultados.",
                    "search": '<div class="icon-addon addon-md"><label for="search" class="ion-search"></label>',
                    "paginate": {
                        first: "Primero",
                        previous: "Anterior",
                        next: "Siguiente",
                        last: "Ultimo"
                    },
                    "lengthMenu": " _MENU_ ",
                    "info": "Mostrando registros del _START_ al _END_ de _TOTAL_ registros totales.",
                    "infoEmpty": "No hay registros para mostrar.",
                },
                "ajax": {
                    url: '@Url.Action("ObtenerTabla", "Producto")',
                    "type": "GET",
                    "datatype": "json",
                    "error": function (xhr, status, error) { }
                },
                columns: [
                    { "data": "Id", "autoWidth": true },
                    { "data": "Nombre", "autoWidth": true },
                    { "data": "Descripcion", "autoWidth": true },
                    { "data": "Categoria", "autoWidth": true },
                    {
                        data: null,
                        render: function (data) {
                            if (data.Activo) {
                                return '<div class="label label-success">Si</div>';
                            } else {
                                return '<div class="label label-danger">No</div>';
                            }
                        }
                    },
                    {
                        "data": "null",
                        render: function (data, type, row, meta) {

                            var activar = "";
                            var clase = "";

                            if (row.Activo) {
                                clase = ""
                                activar = '<li><a href="javascript: void(0)" data-producto="' + row.Id + '" name="Desactivar"><i class="fas fa-ban"></i> Desactivar</a>';
                            } else {
                                clase = "disabled";
                                activar = '<li><a href="javascript: void(0)" data-producto="' + row.Id + '" name="Activar"><i class="fas fa-check-circle"></i> Activar</a>';
                            }


                            return '<div class="btn-group"> <button class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Acciones <i class="fa fa-caret-down fa-lg"></i> </button>' +
                                '<ul class="dropdown-menu">' +
                                '<li class="' + clase + '"><a class="' + clase + '" href="javascript: void(0)" data-producto="' + row.Id + '" name="Edit"><i class="fas fa-edit"></i> Editar</a>' +
                                '<li><a href="javascript: void(0)" data-producto="' + row.Id + '" name="Ver"><i class="fas fa-eye"></i> Ver</a>' +
                                activar +
                                '</ul></div>';
                        }
                    }
                ]
            });


        });

        $(document).on('click', '.js-crear', function () {
            window.location.href = '@Url.Action("CrearProducto","Producto")';
            
        });


        $('#dtProductos tbody').on('click', 'a[name="Edit"]', function () {

            var isDisabled = $(this);

            if (isDisabled[0].className !== "disabled") {
                var producto = $(this).data('producto');
                window.location.href = '@Url.Action("EditarProducto","Producto")?idProducto='+ producto;
            }

        });

        $('#dtProductos tbody').on('click', 'a[name="Ver"]', function () {
            var producto = $(this).data('producto');

            var data = { idProducto: producto };
            MostrarModal('/Producto/VerProducto', data);
            
        });

        $('#dtProductos tbody').on('click', 'a[name="Desactivar"]', function () {

            var producto = $(this).data('producto');

            var data = { Id: producto };

            DeshabilitarRegistro(data, dtProductos, '/Producto/CambiarEstado/', 'Desea inhabilitar el producto?','text-danger');

        });

        $('#dtProductos tbody').on('click', 'a[name="Activar"]', function () {

            var producto = $(this).data('producto');

            var data = { Id: producto };

            DeshabilitarRegistro(data, dtProductos, '/Producto/CambiarEstado/', 'Desea habilitar el producto?','text-primary');



        });


    </script>


}

BaseProject/Views/Producto/VerProducto.cshtml
@model BaseProject.Models.Producto.ProductoViewModel

<div class="panel panel-dark">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-plus-square fa-fw"></i> Producto @Model.Nombre </h1>
    </div>
    <div class="panel-body">
        <div class="row">

            <div class="col col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <form id="frm" method="post">
                    <div class="form-horizontal">

                        <div class="form-group">
                            <label class="col-lg-12">Nombre: <strong>@Model.Nombre</strong></label>

                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Descripcion: <strong>@Model.Descripcion</strong></label>

                        </div>

                        <div class="form-group">
                            <label class="col-lg-12">Categoria: <strong>@Model.Categoria</strong></label>
                        </div>

                    </div>

                </form>
            </div>
            <div class="col col-lg-6 col-md-6 col-sm-12 col-xs-12">

                <img src="@Url.Action("ObtenerImagen","Producto")?idProducto=@Model.Id" style="width:100%;height:100%" />

            </div>
        </div>
        <div class="row">
            <div class="col col-lg-12 col-md-12 col-xs-12">

                <table class="table table-reponsive table-bordered" id="dtMateriales" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th data-class="expand">Materiales</th>
                            <th data-class="expand">Formula</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var a in Model.lstDetalle)
                        {
                            <tr>
                                <th>@a.Material</th>
                                <th>@a.Formula</th>
                            </tr>
                        }

                    </tbody>
                </table>

            </div>
        </div>

        <div class="widget-footer">
            <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
        </div>


        </div>
</div>