BaseProject/Models/TipoMedida/TipoMedidaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.TipoMedida
{
    public class TipoMedidaViewModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Prefijo { get; set; }
    }
}

BaseProject/Controllers/TipoMedidaController.cs
using BaseProject.Models.TipoMedida;
using BaseProject.Repositories.TipoMedidaManager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    public class TipoMedidaController : Controller
    {
        private readonly ITipoMedidaManager _tipoMedida;
        
        public TipoMedidaController(ITipoMedidaManager tipoMedida)
        {
            _tipoMedida = tipoMedida;
        }
        // GET: TipoMedida
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetTabla()
        {
            var data = _tipoMedida.ObtenerListado();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearTipoMedida()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CrearTipoMedida(TipoMedidaViewModel model)
        {
            var response = _tipoMedida.CrearTipoMedida(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarTipoMedida(int idTipoMedida)
        {
            var model = _tipoMedida.ObtenerTipoMedida(idTipoMedida);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult EditarTipoMedida(TipoMedidaViewModel model)
        {
            var response = _tipoMedida.EditarTipoMedida(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

    }
}

BaseProject/Views/TipoMedida/CrearTipoMedida.cshtml
@model BaseProject.Models.TipoMedida.TipoMedidaViewModel

<div class="panel panel-dark">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-plus-square fa-fw"></i> Nuevo Tipo Medida </h1>
    </div>
    <div class="panel-body">
        <form id="frm" method="post">
            <div class="form-horizontal">

                <div class="form-group">
                    <label class="col-lg-12">Nombre: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-12">Prefijo: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.Prefijo, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="widget-footer">
                    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
                    <button type="submit" class="btn btn-success"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
                </div>

            </div>

        </form>

    </div>
</div>

<script>

    $(document).ready(function (){

        $('#frm').validate({
            ignore: [],
            rules: {
                Nombre: {
                    required: true,
                    maxlength: 200
                },
                Prefijo: {
                    required: true,
                    maxlength: 10
                }
            },
            messages: {
                Nombre: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 200 caracteres"
                },
                Prefijo: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 10 caracteres"
                }
            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("CrearTipoMedida","TipoMedida")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },
                    success: function (data) {
                        if (data.Ok) {
                            $("#myModal").modal("hide");
                            dtTipoMedida.ajax.reload(null, false);
                            AlertaAjax(data);
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;
            }
        });

    });

</script>

BaseProject/Views/TipoMedida/EditarTipoMedida.cshtml
@model BaseProject.Models.TipoMedida.TipoMedidaViewModel

<div class="panel panel-dark">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-edit fa-fw"></i> Editar Tipo Medida @Model.Nombre </h1>
    </div>
    <div class="panel-body">
        <form id="frm" method="post">
            <div class="form-horizontal">

                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    <label class="col-lg-12">Nombre: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-12">Prefijo: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.Prefijo, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="widget-footer">
                    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
                    <button type="submit" class="btn btn-success"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
                </div>

            </div>

        </form>

    </div>
</div>

<script>

    $(document).ready(function (){

        $('#frm').validate({
            ignore: [],
            rules: {
                Nombre: {
                    required: true,
                    maxlength: 200
                },
                Prefijo: {
                    required: true,
                    maxlength: 10
                }
            },
            messages: {
                Nombre: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 200 caracteres"
                },
                Prefijo: {
                    required: "Campo requerido",
                    maxlength: "Ingrese un maximo de 10 caracteres"
                }
            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("EditarTipoMedida","TipoMedida")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },
                    success: function (data) {
                        if (data.Ok) {
                            $("#myModal").modal("hide");
                            dtTipoMedida.ajax.reload(null, false);
                            AlertaAjax(data);
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;
            }
        });

    });

</script>

BaseProject/Views/TipoMedida/Index.cshtml
<div class="panel panel-dark">
    <div class="panel-heading">
        <div class="panel-control">

            <a class="btn btn-success js-crear"><i class="fa fa-plus-circle fa-fw"></i> Nuevo Tipo Medida</a>
        </div>
        <h3 class="panel-title"> <i class="fas fa-ruler-combined fa-fw"></i>Lista de Tipos de Medidas</h3>
    </div>

    <div class="panel-body">
        <table class="table table-responsive table-bordered table-hover" style="width:100%;" id="dtTipoMedida">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Prefijo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>


    </div>
</div>

@section Scripts{

    <script>

        var dtTipoMedida;

        $(document).ready(function () {


            dtTipoMedida = $('#dtTipoMedida').DataTable({
                autoWidth: true,
                responsive: true,
                language: {
                    "emptyTable": "No se encontraron resultados.",
                    "search": '<div class="icon-addon addon-md"><label for="search" class="ion-search"></label>',
                    "paginate": {
                        first: "Primero",
                        previous: "Anterior",
                        next: "Siguiente",
                        last: "Ultimo"
                    },
                    "lengthMenu": " _MENU_ ",
                    "info": "Mostrando registros del _START_ al _END_ de _TOTAL_ registros totales.",
                    "infoEmpty": "No hay registros para mostrar.",
                },
                "ajax": {
                    url: '@Url.Action("GetTabla", "TipoMedida")',
                    "type": "GET",
                    "datatype": "json",
                    "error": function (xhr, status, error) { }
                },
                columns: [
                    { "data": "Id", "autoWidth": true },
                    { "data": "Nombre", "autoWidth": true },
                    { "data": "Prefijo", "autoWidth": true },
                    {
                        "data": "null",
                        render: function (data, type, row, meta) {
                            return '<div class="btn-group"> <button class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Acciones <i class="fa fa-caret-down fa-lg"></i> </button>' +
                                '<ul class="dropdown-menu">' +
                                '<li><a href="javascript: void(0)" data-tipomedida="' + row.Id + '" name="Edit">Editar</a>' +
                                '</ul></div>';
                        }
                    }
                ]
            });


        });

        $(document).on('click', '.js-crear', function () {

            $.ajax({
                url: "@Url.Action("CrearTipoMedida", "TipoMedida")",
                type: "GET",
                beforeSend: function() {
                    LoadWaitNotification();
                },
                complete: function() {
                    UnloadWaitNotification();
                },
                success: function (data) {
                    $("#modalBody").html(data);
                    $('#myModal').modal({ backdrop: 'static', keyboard: false })
                    $("#myModal").modal("show");
                }
            });


        });


        $('#dtTipoMedida tbody').on('click', 'a[name="Edit"]', function () {

            var tipomedida = $(this).data('tipomedida');
            $.ajax({
                    url: "@Url.Action("EditarTipoMedida", "TipoMedida")",
                    type: "GET",
                    beforeSend: function() {
                        LoadWaitNotification();
                    },
                    complete: function() {
                        UnloadWaitNotification();
                    },
                    data: { idTipoMedida: tipomedida },
                    success: function (data) {
                        $("#modalBody").html(data);
                        $('#myModal').modal({ backdrop: 'static', keyboard: false })
                        $("#myModal").modal("show");
                    }
                });

        });




    </script>


}